services:
  backend:
    image: juanne123/finances-backend:d45e369
    environment:
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: finances
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_CREATE_DROP: update
      SECRET_KEY: 8a1cb083feb4f2f466da5d352245b478a46c57f7cf2da1536ad46ebdd4a37071
      JWT_EXPIRATION_TIME: 3600000
      CORS_ALLOWED_ORIGINS: http://localhost:4200
      SWAGGER_ENABLED: false
    ports:
      - "8080:8080"
    depends_on:
      - database

  frontend:
    image: juanne123/finances-frontend:c35a7e8
    ports:
      - "4200:4200"
    depends_on:
      - backend

  database:
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_DB: finances
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
